image: python:3.8.6-alpine3.12

stages:
  - test
  - publish

cache:
  paths:
    - .pip
before_script:
  - python --version
  - pip --cache-dir=.pip install -e . && pip install -e '.[dev]'

python36:
  image: python:3.6-slim
  stage: test
  script: tox -e py36
  after_script:
    - bash <(curl -s https://codecov.io/bash)


python37:
  image: python:3.7-slim
  stage: test
  script: tox -e py37

python38:
  image: python:3.8-slim
  stage: test
  script: tox -e py38


publish:
  stage: publish
  image: 'python:3.8'
  script:
    - python setup.py upload
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success