stages:
#  - test
  - publish

cache:
  paths:
    - .pip
before_script:
  - python --version
  - pip --cache-dir=.pip install -e . && pip install -e '.[dev]'

#test:
#  stage: test


publish:
  stage: publish
  image: 'python:3.8'
  script:
    - python setup.py publish
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success